ofreleases:
 -
  version: 0.6.1
  date: 2010-02-11T01:17:27-08:00
 -
  version: 0.6.2
  date: 2010-11-17T11:22:37-08:00
 -
  version: 0.7.0
  date: 2011-07-21T09:52:34-07:00
 -
  version: 0.7.1
  date: 2012-05-28T09:32:18-07:00
 -
  version: 0.7.2
  date: 2012-10-20T10:13:39-07:00
 -
  version: 0.7.3
  date: 2012-11-14T14:39:05-08:00
 -
  version: 0.7.4
  date: 2013-02-15T01:10:38-08:00
 -
  version: 0.8.0
  date: 2013-08-11T05:45:26-08:00